spring:
  application:
    name: checkout
  datasource:
    url: jdbc:postgresql://localhost:5432/checkout
    username: checkout
    password: checkout123
  jpa:
    generate-ddl: false
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: none
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true